(deffacts zwierzeta
    (pies Burek)
    (umaszczenie Burek rude)
    (oczy Burek niebieskie)
    (pies Maksiu)
    (umaszczenie Maksiu czarne)
    (oczy Maksiu brazowe)
    (kot Mruczek)
    (umaszczenie Mruczek niebieskie)
    (oczy Mruczek niebieskie)
    (dzik Teutates)
    (umaszczenie Teutates plowe)
    (oczy Teutates brazowe)
)